### ISSUE TITLE
Stuck at " Starting qBittorrent Service"

### ISSUE THREAD

**Issue by ehcorn** [wiorca/docker-windscribe-qbittorrent#1]
I've setup the docker container, log says it's signing into windscribe fine but I can't connect to the webUI (ports are opened at 8080, as default) I'm a little confused about the inheriting the config file; my interpretation is that I need to launch another qbittorrent docker, store its config file somewhere and shut it down, then launch this docker and it should pull the config from that file. I have a feeling this is where I've gone wrong.

**Comment by wiorca** [comment]
"Starting qBittorrent Service" is the last message you will see if it successfully starts.  The container also has a health check.  What is the state after a few minutes of the container running?

The qbittorrent client should create a default configuration file the first time it runs under /config (inside the container).  Make sure to forward the host port 8080 to container port 8080, or use the container's internal IP.

**Comment by ehcorn** [comment]
I get this:

spawn windscribe status windscribe -- pid: 36, status: running, uptime: 5m, %cpu: 0.0, %mem: 0.4[0m IP: 208.78.41.6[0m [32mCONNECTED -- CA-W stealth (80)[0m Health OK PING google.com (172.217.3.174) 56(84) bytes of data. 64 bytes from sea15s11-in-f14.1e100.net (172.217.3.174): icmp_seq=1 ttl=118 time=10.1 ms --- google.com ping statistics --- 1 packets transmitted, 1 received, 0% packet loss, time 0ms rtt min/avg/max/mdev = 10.067/10.067/10.067/0.000 ms Network is up qbittorrent-nox is running

but if I connect it just times out. 8080 is open in the docker, I've been using portainer to check everything

**Comment by wiorca** [comment]
Can you run, on your host:

docker container inspect [container_name]
docker container port [container_name]

**Comment by ehcorn** [comment]
I think I found the issue. The network is setup on 172.17.0.0 but I use 192.168.0.0 can that be changed with environment variables?



[
    {
        "Id": "560050b2bc6a0db19a34e62dc03e5170c7d7412eb870627c73e1f05e7c763558",
        "Created": "2020-09-28T04:26:48.977806524Z",
        "Path": "/bin/bash",
        "Args": [
            "/opt/scripts/vpn-startup.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 10444,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-09-28T04:26:51.930777424Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2020-09-28T07:27:07.801574637-07:00",
                        "End": "2020-09-28T07:27:11.393243474-07:00",
                        "ExitCode": 0,
                        "Output": "spawn windscribe status\r\nwindscribe -- pid: 36, status: running, uptime: 10h 0m, %cpu: 0.0, %mem: 0.4\u001b[0m\r\nIP: 208.78.41.167\u001b[0m\r\n\u001b[32mCONNECTED -- CA-W stealth (80)\u001b[0m\r\nHealth OK\nPING google.com (172.217.3.174) 56(84) bytes of data.\n64 bytes from sea15s11-in-f14.1e100.net (172.217.3.174): icmp_seq=1 ttl=118 time=26.3 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 26.279/26.279/26.279/0.000 ms\nNetwork is up\nqbittorrent-nox is running\n"
                    },
                    {
                        "Start": "2020-09-28T07:32:11.541400149-07:00",
                        "End": "2020-09-28T07:32:14.259349924-07:00",
                        "ExitCode": 0,
                        "Output": "spawn windscribe status\r\nwindscribe -- pid: 36, status: running, uptime: 10h 5m, %cpu: 0.0, %mem: 0.4\u001b[0m\r\nIP: 208.78.41.167\u001b[0m\r\n\u001b[32mCONNECTED -- CA-W stealth (80)\u001b[0m\r\nHealth OK\nPING google.com (172.217.3.174) 56(84) bytes of data.\n64 bytes from sea15s11-in-f174.1e100.net (172.217.3.174): icmp_seq=1 ttl=118 time=11.6 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 11.622/11.622/11.622/0.000 ms\nNetwork is up\nqbittorrent-nox is running\n"
                    },
                    {
                        "Start": "2020-09-28T07:37:14.406065449-07:00",
                        "End": "2020-09-28T07:37:17.086289187-07:00",
                        "ExitCode": 0,
                        "Output": "spawn windscribe status\r\nwindscribe -- pid: 36, status: running, uptime: 10h 10m, %cpu: 0.0, %mem: 0.4\u001b[0m\r\nIP: 208.78.41.167\u001b[0m\r\n\u001b[32mCONNECTED -- CA-W stealth (80)\u001b[0m\r\nHealth OK\nPING google.com (172.217.3.174) 56(84) bytes of data.\n64 bytes from sea15s11-in-f174.1e100.net (172.217.3.174): icmp_seq=1 ttl=118 time=11.4 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 11.408/11.408/11.408/0.000 ms\nNetwork is up\nqbittorrent-nox is running\n"
                    },
                    {
                        "Start": "2020-09-28T07:42:17.259878524-07:00",
                        "End": "2020-09-28T07:42:20.034300449-07:00",
                        "ExitCode": 0,
                        "Output": "spawn windscribe status\r\nwindscribe -- pid: 36, status: running, uptime: 10h 15m, %cpu: 0.0, %mem: 0.4\u001b[0m\r\nIP: 208.78.41.167\u001b[0m\r\n\u001b[32mCONNECTED -- CA-W stealth (80)\u001b[0m\r\nHealth OK\nPING google.com (172.217.3.174) 56(84) bytes of data.\n64 bytes from sea15s11-in-f14.1e100.net (172.217.3.174): icmp_seq=1 ttl=118 time=11.7 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 11.723/11.723/11.723/0.000 ms\nNetwork is up\nqbittorrent-nox is running\n"
                    },
                    {
                        "Start": "2020-09-28T07:47:20.178411737-07:00",
                        "End": "2020-09-28T07:47:23.094673224-07:00",
                        "ExitCode": 0,
                        "Output": "spawn windscribe status\r\nwindscribe -- pid: 36, status: running, uptime: 10h 20m, %cpu: 0.0, %mem: 0.4\u001b[0m\r\nIP: 208.78.41.167\u001b[0m\r\n\u001b[32mCONNECTED -- CA-W stealth (80)\u001b[0m\r\nHealth OK\nPING google.com (172.217.3.174) 56(84) bytes of data.\n64 bytes from sea15s11-in-f174.1e100.net (172.217.3.174): icmp_seq=1 ttl=118 time=11.8 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 11.782/11.782/11.782/0.000 ms\nNetwork is up\nqbittorrent-nox is running\n"
                    }
                ]
            }
        },
        "Image": "sha256:e5dfbeb116384be905f7b6bc6795379e150979a296d0d3f18642ed55d2f3670e",
        "ResolvConfPath": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/containers/560050b2bc6a0db19a34e62dc03e5170c7d7412eb870627c73e1f05e7c763558/resolv.conf",
        "HostnamePath": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/containers/560050b2bc6a0db19a34e62dc03e5170c7d7412eb870627c73e1f05e7c763558/hostname",
        "HostsPath": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/containers/560050b2bc6a0db19a34e62dc03e5170c7d7412eb870627c73e1f05e7c763558/hosts",
        "LogPath": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/containers/560050b2bc6a0db19a34e62dc03e5170c7d7412eb870627c73e1f05e7c763558/560050b2bc6a0db19a34e62dc03e5170c7d7412eb870627c73e1f05e7c763558-json.log",
        "Name": "/docker-windscribe-qbittorrent",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/Media:/data",
                "/volume1/Docker/qbittorrent:/config",
                "/volume1/Media:/media"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "AUDIT_WRITE",
                "CHOWN",
                "DAC_OVERRIDE",
                "FOWNER",
                "FSETID",
                "KILL",
                "MKNOD",
                "NET_ADMIN",
                "NET_BIND_SERVICE",
                "NET_RAW",
                "SETFCAP",
                "SETGID",
                "SETPCAP",
                "SETUID",
                "SYS_CHROOT"
            ],
            "CapDrop": [
                "AUDIT_CONTROL",
                "BLOCK_SUSPEND",
                "DAC_READ_SEARCH",
                "IPC_LOCK",
                "IPC_OWNER",
                "LEASE",
                "LINUX_IMMUTABLE",
                "MAC_ADMIN",
                "MAC_OVERRIDE",
                "NET_BROADCAST",
                "SYSLOG",
                "SYS_ADMIN",
                "SYS_BOOT",
                "SYS_MODULE",
                "SYS_NICE",
                "SYS_PACCT",
                "SYS_PTRACE",
                "SYS_RAWIO",
                "SYS_RESOURCE",
                "SYS_TIME",
                "SYS_TTY_CONFIG",
                "WAKE_ALARM"
            ],
            "Capabilities": null,
            "Dns": [
                "8.8.8.8"
            ],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": true,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/0c0374920299737e5f591ed4cbbe5bfdbaeeebf76774f985edbfc7fea42f5bb0-init/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/7563dca69e7fade4031bbec89861bd57e2128a940ad226d4ab17d7ec171306c4/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/a9864dc5197f2686fbb3857b05e5dc16409d4040c8d7b3afa511bfdae0134fc0/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/ce9870da6acdc4c923a151c89da3783ecdc313ab9aa0ece1d03c1f4d3e3689d2/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/5b2a670ac22e80bf075b7a5c733e54f2982231b956f992b3a50221507bc3497e/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/01c6e5be8c3d01ae66e814793af1db7dc64a071cf60fb9411476dd7108de3b32/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/fcfaf10df13c739c4b74f2c35de0c81ca7b4c88c00063be20bc689424c026362/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/35290e81911281308973cca248a0a6dd457ab4227c7104831e5cc90256733984/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/7c61508fd0b8464cea7c28bec286ea9ae0daa6e26932e8a8c61959a4e4dbe33b/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/009ba17d2e07069458747a9fdfe7e000593b283bc9a18fc3c425e94874715080/diff",
                "MergedDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/0c0374920299737e5f591ed4cbbe5bfdbaeeebf76774f985edbfc7fea42f5bb0/merged",
                "UpperDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/0c0374920299737e5f591ed4cbbe5bfdbaeeebf76774f985edbfc7fea42f5bb0/diff",
                "WorkDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/0c0374920299737e5f591ed4cbbe5bfdbaeeebf76774f985edbfc7fea42f5bb0/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/Media",
                "Destination": "/media",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/Media",
                "Destination": "/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/Docker/qbittorrent",
                "Destination": "/config",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "82473d999b3a",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TZ=America/Vancouver",
                "WINDSCRIBE_USERNAME=XXXXXX",
                "WINDSCRIBE_PASSWORD=XXXXXX",
                "WINDSCRIBE_PORT=80",
                "WINDSCRIBE_PORT_FORWARD=9999",
                "WINDSCRIBE_LOCATION=US",
                "WINDSCRIBE_FIREWALL=on",
                "PUID=1000",
                "WINDSCRIBE_PROTOCOL=stealth",
                "WINDSCRIBE_LANBYPASS=on",
                "PGID=1000",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "HOME=/config"
            ],
            "Cmd": [
                "/bin/bash",
                "/opt/scripts/vpn-startup.sh"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "/opt/scripts/vpn-health-check.sh || exit 1"
                ],
                "Interval": 300000000000,
                "Timeout": 20000000000
            },
            "Image": "wiorca/docker-windscribe-qbittorrent:latest",
            "Volumes": {
                "/config": {},
                "/data": {},
                "/media": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3b77acdfedea6e35f9a341ae1f0a66e795b2b4ea2da563563fc9c6b6df58b2ea",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/3b77acdfedea",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "11300b3773535aace68dad3a7e86d0fd1135272702288adfbdde020daaccea5f",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.8",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "XXXXXX",
            "Networks": {
                "bridge": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "0fb5c1caa625943c571d8211db7356dd3223f4caebf3ae924f3c23cba8bd3ec2",
                    "EndpointID": "11300b3773535aace68dad3a7e86d0fd1135272702288adfbdde020daaccea5f",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.8",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:08",
                    "DriverOpts": null
                }
            }
        }
    }
]


8080/tcp -> 0.0.0.0:8080

**Comment by wiorca** [comment]
That all looks pretty good to me.  The 172 address is the internal address on your docker bridge network.  I'd try http://[internal docker address]:8080 to make sure that works.

**Comment by ehcorn** [comment]
Ah I checked some of my other containers, same 172 address thing. if I try connecting directly to the docker host IP address same as I do everything else port 8080 but it doesn't connect. if I shutdown this docker and launch the linuxserver.io qbittorrent docker it starts up and I can connect fine, if that helps narrow down troubleshooting.

**Comment by StarWhiz** [comment]
I also have the same issue as @ehcorn 

Hello just tried spinning this container up today. Like ehcorn the linuxserver.io container works for me but this doesn't. I can't connect to the webui via http://<dockerhost IP address>:8080

I get
`docker container port 222
8080/tcp -> 0.0.0.0:8080
`

and also get
`
root@222d6b81f49d:/opt/scripts# ./app-health-check.sh
qbittorrent-nox is running
`

**Comment by wiorca** [comment]
Odd.  I'm not sure if qbittorrent is starting if your config directory is empty.  Try deleting, purging, then recreating the container.

Testing the image today, localhost:8080 works just fine :).

I use a reverse proxy to access the web UI inside the container.

The DNS error message is expected.  I override the DNS manually to stop the standard docker DNS config from having an effect.

**Comment by StarWhiz** [comment]
Thanks @wiorca I'll try giving caddy reverse proxy a shot to see if I can access it.

**Comment by wiorca** [comment]
You must always expose a port (so localhost:8080 will work) or access it internally over the docker network (eg, from another container).  Windscribe itself has a firewall which prevents any other communication, and docker has its own constraints.

**Comment by StarWhiz** [comment]
That makes sense to me now. Thank you so much wiorca. if I get this working I can help @ehcorn :)

**Comment by wiorca** [comment]
Good luck :)!  Re-open this if nothing works.
