### ISSUE TITLE
qBittorrent not starting, Cannot call seek on a sequential device error

### ISSUE THREAD

**Issue by seriousuxx** [wiorca/docker-windscribe-qbittorrent#2]
Hi Guys, 

when starting the service it looks all ok, but then I don't get the qbittorrent interface.
I've checked the logs, but something is going on. Do I have to configure it differently? 

Starting windscribe ... OK

spawn windscribe login

Windscribe Username: XXXXXXXXXX

Windscribe Password: 

-/|\Logged In

Login Successful

spawn windscribe lanbypass on

N bybass set to: on

LAN bypass set

spawn windscribe protocol UDP

Default protocol changed to: UDP

Protocol set successfully

spawn windscribe port 80

Default port changed to: 80

Port set successfully

spawn windscribe firewall on

Firewall mode changed to: on

Firewall Enabled

Firewall is on

spawn windscribe connect

-Connecting to Netherlands Amsterdam Tulip (udp:80)

/|Firewall Enabled

/etc/resolv.conf is not a symlink, this may break DNS

\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-/|\-Connected to Netherlands Amsterdam Tulip

VPN connected

Starting qBittorrent Service

QIODevice::seek (QFile, "/config/.local/share/data/qBittorrent/logs/qbittorrent.log"): Cannot call seek on a sequential device

Does someone know what's going on?

**Comment by wiorca** [comment]
It looks like your config directory isn't mapped in a writeable way?
