### ISSUE TITLE
Read but not Write perms to /data folder

### ISSUE THREAD

**Issue by Ltek** [wiorca/docker-windscribe-qbittorrent#5]
just setup the container, replaced UID & GID with my local admin account. QBittorrent seems to have R/W access to /config but not /data  ... the same folder structure and acct is used in my linuxserver.io Deluge container and that works fine.

Is there something different I need to do for yours?

thx

**Comment by wiorca** [comment]
Make sure the UID and GID numbers are correct.  That should work :).
