### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by ronioncloud** [wiorca/docker-windscribe-qbittorrent#6]
Docker logs:
"Starting windscribe ... OK
spawn windscribe login
Windscribe Username: username
Windscribe Password: 
Error running "login"
Unexpected EOF
"
sudo docker create \
  --name=docker-windscribe-qbittorrent \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/New_York \
  -e WINDSCRIBE_USERNAME=myusernamehere \   #I also tried with quotes. "myusernamehere"
  -e WINDSCRIBE_PASSWORD=mypasswordhere \   #I also tried with quotes. "mypasswordhere"
  -e WINDSCRIBE_PROTOCOL=stealth \
  -e WINDSCRIBE_PORT=80 \
  -e WINDSCRIBE_LOCATION=BR \
  -e WINDSCRIBE_LANBYPASS=on \
  -e WINDSCRIBE_FIREWALL=on \
  -v /home/ubuntu/test/docker-windscribe-qbittorrent/config:/config \
  -v /home/ubuntu/test/docker-windscribe-qbittorrent/data:/data \
  --dns 8.8.8.8 \
  -p 8080:8080 \
  --cap-add NET_ADMIN \
  --restart unless-stopped \
  wiorca/docker-windscribe-qbittorrent

**Comment by wiorca** [comment]
Odd, this is new.  It could be it failed to connect to the windscribe servers.

**Comment by wiorca** [comment]
When I see issues like this, I recreate the image, and pull a fresh copy from docker hub.  Normally that clears things up.  Honestly not sure why yet
